#-------------------------------
# General Site Settings

title: Eric Moon's Blog
logo: 
author: Eric Moon

copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Portfolio, link: '/portfolio'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Eric Moon's<br/>Blog


#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "/subway"


# Portfolio Page
portfolio-label:
- {
    title : "Data Analysis",
    type : "DA"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "https://subway-project.vercel.app/"
    portfolio-type:
     - type: "DA"
     - type: "WEB"
 
#-------------------------------
